require 'my_project'

describe 'MyProject' do
  it 'should be awesome' do 
    expect(are_you_awesome?).to be_true
  end
  it 'should be generated by pair programming' do 
    expect(collaboration_technique).to eq 'Pair Programming'
  end
  it 'should be developed via BDD' do 
    expect(development_style).to eq 'BDD'
  end
end